### ISSUE TITLE
"true" e "false" come stringhe

### ISSUE THREAD

**Issue by davcri** [NetRider/MySite#2]
Guardando questo file: https://github.com/NetRider/MySite/blob/master/Classes/Control/UserAccessController.php#L54

ho notato che usi `"true"` e `"false"` come valori di ritorno. È un errore di battitura, oppure hai proprio necessità di ritornare delle stringhe ?

**Comment by NetRider** [comment]
Si era davvero brutto. Ho modificato la classe astratta View (eredita da tutte le classi View di ciascun Controller) e adesso al suo interno esiste un metodo responseAjaxCall($data). Quindi ogni volta che il controller deve notificare se la richiesta dalle chiamate Ajax è andate a buon fine può farlo attraverso la sua view con questo metodo. Inoltre adesso la comunicazione è molto flessibile. Se prima poteva rispondere solamente con una stringa "true" o "false" adesso può rispondere qualsiasi tipo di dato. Anche livello di pulizia di codice c'è stato un notevole miglioramento (sono scoparsi molti if con annessi return"true" e return "false). Inoltre ora non utilizzo più le stringhe "true" e "false" ma i valori boleani ( come è giusto che sia XD)
